### ISSUE TITLE
Check array value error

### ISSUE THREAD

**Issue by OskarLeszczynski** [marcingrzejszczak/jsonassert#10]
I found this issue when I was using accurest library. After some investigation I wrote test in jsonassert based on code generated by accurest and it didn't pass (code below). 

@Shared String json12 = '''{ "some_list" : ["name1", "name2"] }'''

    @Unroll
    def 'should manage to parse array with string values'() {
        expect:
            assertThat(JsonPath.parse(json12)).array("some_list").contains("name1").value()
            assertThat(JsonPath.parse(json12)).array("some_list").contains("name2").value()
    }

Result:
java.lang.AssertionError: Expected JSON to match JSON Path <$.some_list[ * ][ * ]> but it didn't
	at org.assertj.core.api.AbstractAssert.failWithMessage(AbstractAssert.java:112)
	at com.toomuchcoding.jsonassert.JsonPathAssert.value(JsonPathAssert.java:143)
	at com.toomuchcoding.jsonassert.JsonAssertionWithAssertJJava8Spec.should manage to parse array with string values(JsonAssertionWithAssertJJava8Spec.groovy:206)

I think that this is issue of jsonassert but maybe I'm wrong and the error is in accurest?

**Comment by marcingrzejszczak** [comment]
Hi! I think it's related to https://github.com/marcingrzejszczak/jsonassert/issues/9. I'm working on that in Accurest too.

**Comment by marcingrzejszczak** [comment]
From what I see `contains` is broken in these cases so in current `0.4.3` version things are fixed with `arrayField` method.

**Comment by OskarLeszczynski** [comment]
Thanks for your quick reaction :)

**Comment by marcingrzejszczak** [comment]
@OskarLeszczynski  - can you check that with Accurest SNAPSHOT? You have to unfortunately build it yourself :/
