### ISSUE TITLE
Using dots in json keys generate wrong JsonPath

### ISSUE THREAD

**Issue by joaquinxxi** [marcingrzejszczak/jsonassert#15]
The following json:

`{`
`  "category": 10,`
`  "category.subcategory": 5,`
`  "category.subcategory.subcategory2": 10`
`}`

Generates following json asserts:

`assertThatJson(parsedJson).field(“category").isEqualTo(10);`
`assertThatJson(parsedJson).field(“category.subcategory").isEqualTo(5);`
`assertThatJson(parsedJson).field(“category.subcategory.subcategory2").isEqualTo(10);`

Which should be translated into the following Json paths:

`$['category']`
`$['category.subcategory']`
`$['category.subcategory.subcategory2']`

**Comment by marcingrzejszczak** [comment]
Related to https://github.com/spring-cloud/spring-cloud-contract/issues/269

**Comment by marcingrzejszczak** [comment]
Will be solved in spring-cloud/spring-cloud-contract#269
