### ISSUE TITLE
JsonAsserter.isEmpty() does not work for empty objects

### ISSUE THREAD

**Issue by kaidowei** [marcingrzejszczak/jsonassert#28]
`assertThatJson(parsedJson).field("['output']").isEmpty();` crashes with Caused by: java.lang.ClassCastException: net.minidev.json.JSONObject cannot be cast to net.minidev.json.JSONArray

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/marcingrzejszczak/jsonassert/pull/29
