### ISSUE TITLE
jonsassert fails on isEqualTo when no field is provided

### ISSUE THREAD

**Issue by adamsiemion** [marcingrzejszczak/jsonassert#30]
JsonAssertion.assertThatJson("{\"x\":\"y\"}").isEqualTo("{\"x\":\"y\"}");

or

    JsonAssertion.assertThatJson("{}").isEqualTo("{}");

fails due to a mysterious exception:

    java.lang.RuntimeException: com.jayway.jsonpath.InvalidPathException: Path must not end with a '.' or '..'

**Comment by marcingrzejszczak** [comment]
Yeah, it was never intended to work that way. It seems that either the fluent API should not allow it or there should be a better exception message

**Comment by marcingrzejszczak** [comment]
Currently have no bandwith to fix this. In general it was never intended to work like that
