### ISSUE TITLE
Older version of asm transitively included

### ISSUE THREAD

**Issue by bono007** [marcingrzejszczak/jsonassert#34]
The `compile` dependency on `com.jayway.jsonpath:json-path` transitively brings in an old version of `org.w2.asm:asm` (5.x). This can be problematic for some Spring applications that use a newer version of `asm` (7.x). For example - [this dependency convergence](https://github.com/spring-cloud/spring-cloud-contract/issues/1561) error that is reported in a maven environment.

The old asm is brought in via `json-path -> json-smart -> smart-asserter` and ideally it would be fixed as in one of those. However, they are all inactive so the best we can do is exclude it from here out. 

This can be a breaking change for consuming applications not supplying an `asm` lib (non Spring based apps). For that reason this should be released with a `major` version number bump.

**Comment by marcingrzejszczak** [comment]
We've decided to 

- provide a shaded artifact with all the deps including asm
- leave the current artifact that can have the deps exluded
