### ISSUE TITLE
Upgrade JsonPath library to 2.5

### ISSUE THREAD

**Issue by bono007** [marcingrzejszczak/jsonassert#40]
After 3 years of no release, the [JsonPath](https://github.com/json-path/JsonPath) library finally has been [released](https://github.com/json-path/JsonPath/commit/8ad474399810219f6f2f10433bb977e70f77abfe).

### The Background
The dormancy of JsonPath recently became noticed in Spring Cloud Contract when ["fixing"](https://github.com/spring-cloud/spring-cloud-contract/pull/1568) and then ["unfixing"](https://github.com/spring-cloud/spring-cloud-contract/pull/1578) an issue around the fact that JsonPath's default provider is `json-smart` which in turn brings in an old version of ASM. While upgrading JsonPath will not magically fix the aforementioned issue in Spring Cloud Contract, it will open the door for pull requests to be made into JsonPath. That will allow us more options to do some transitive library hygiene. 

### The Ask
1. Upgrade JsonPath to the latest release.
2. Investigate any ripple of transitive dependencies it carries along. I really would like to see an actual dependency tree report comparison/diff between the version we are using and the latest version. Dependencies are hard and its really easy to get burned by an innocent version bump.

**Comment by marcingrzejszczak** [comment]
Yeah they haven't updated this `json-smart` dependency https://github.com/json-path/JsonPath/commit/70d11a6313a478ef0023295568a4d4cf39ac4fb4#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R19 so upgrading wouldn't fix anything really

**Comment by bono007** [comment]
Agreed. However, it does give us the ability to affect that project in other ways - I am thinking of ensuring that we can use a different out fo the box provider (like Jackson) and get rid of JsonSmart entirely. They have the concept of provider but I am not sure if it will explode when jsonsmart not on the classpath currently. They did make changes to allow this work for OSGI i this release. 

Not a priority right now, though.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/marcingrzejszczak/jsonassert/commit/b83697c75c1188cdf400a6658b7812c7701b9ae8
