### ISSUE TITLE
Upgrade to json-smart 2.4.2 

### ISSUE THREAD

**Issue by bono007** [marcingrzejszczak/jsonassert#41]
@marcingrzejszczak 
I saw [this](https://github.com/spring-projects/spring-boot/issues/25946) in Spring Boot and figured it needs to be updated here as well due to this [vulnerability](https://snyk.io/vuln/SNYK-JAVA-NETMINIDEV-1078499).

Ultimately Spring Cloud Contract will need to pickup an update from here once complete.

**Comment by marcingrzejszczak** [comment]
https://github.com/json-path/JsonPath/issues/687

**Comment by marcingrzejszczak** [comment]
I don't think we should force json-smart to 2.4.2 - it comes transitively from jsonpath

**Comment by bono007** [comment]
Agreed.
