### ISSUE TITLE
generated JSON path is incorrect (jsonassert-0.4.2, java8)

### ISSUE THREAD

**Issue by norbson** [marcingrzejszczak/jsonassert#9]
```
        given:
            String response = '''{"first_name":"existing",
                                  "partners":[
                                      { "role":"AGENT",
                                        "payment_methods":[ "BANK", "CASH" ]
                                      }
                                   ]
                                }'''

        expect:
            assertThatJson(response).array("partners").array("payment_methods").contains("BANK").value()
```

Returns:
`
java.lang.IllegalStateException: Parsed JSON [{"first_name":"existing","partners":[{"role":"AGENT","payment_methods":["BANK"]}]}] doesn't match the JSON path [$.partners[*].payment_methods[*][*]]
`
I think should be 
`
[$.partners[*].payment_methods[*]]
`

**Comment by marcingrzejszczak** [comment]
I think it should be

`$.partners[*].payment_methods[[?(@ == "BANK")]]`

Anyways it's still wrong

**Comment by norbson** [comment]
Of course, I gave an example of intermediate JsonPath which just return list of containing elements without assertion.
Btw, it causes a problem in accurest test generation since this library is used to json assertion

Regards,
Norbert

**Comment by marcingrzejszczak** [comment]
Yeah actually it should be 

`assertThatJson(json).array("partners").array("payment_methods").arrayField().isEqualTo("BANK").value()`

and results in this JSONPath:

`$.partners[*].payment_methods[?(@ == 'BANK')]`

**Comment by norbson** [comment]
great, but now, since this assertion is generated automatically from accurest contract, I assume that we need to raise issue in accurest? (json from example was taken directly from contract expected response)

**Comment by marcingrzejszczak** [comment]
I'm already on it :)
